---
- name: Deploy Latest Portfolio Image from Registry
  hosts: all
  become: yes
  vars:
    project_path: "/opt/portfolio-franciney"

  tasks:
    - name: 1. Ensure project directory exists
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'

    - name: 2. Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - wget
        state: present
        update_cache: yes

    - name: 3. Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: 4. Copy docker-compose.yml to server
      copy:
        src: "{{ playbook_dir }}/../../docker-compose.yml"
        dest: "{{ project_path }}/docker-compose.yml"

    - name: 5. Create docker network
      shell: docker network create app_network || true
      failed_when: false

    - name: 6. Login to GitHub Container Registry
      shell: |
        echo "{{ github_token }}" | docker login ghcr.io -u marcosdgomes --password-stdin
      failed_when: false

    - name: 7. Pull and restart services
      shell: |
        cd {{ project_path }}
        docker-compose pull
        docker-compose up -d